sudo: false
language: elixir
elixir:
  - 1.1.0
otp_release:
  - 18.0
env:
  - MIX_ENV=test
script:
  - mix test --exclude expensive
  - mix test --only expensive
notifications:
  email:
    - dneighman@gmail.com
